### ISSUE TITLE
Enquire about the cell-barcode of vartrix

### ISSUE THREAD

**Issue by zhuxqdoctor** [10XGenomics/vartrix#20]
Hi, I am new to single cell data analysis. I am trying to use vartrix  to call SNVs of Jurkat cell line data from 10X Genomics website. However, I did not find where to download corresponding cell-barcode.tsv of Jurkat cell line data. It seems that all the single cell datasets on 10X Genomics don't have cell-barcode.tsv files. Can you guys tell me how to figure it out. Many thanks.

**Comment by pmarks** [comment]
Hi @zhuxqdoctor,

The barcode.tsv file is available inside the 'Gene/Cell Matrix' tar.gz files.  If you download and un-tar one of those files, you'll see hg19/barcodes.tsv.  That's the right file to use.

Cheers!
Pat

**Comment by zhuxqdoctor** [comment]
Thanks for your reply. I will try it.

Best wishes,
Xiaoqiang




| |
小强
邮箱：zhuxqdoctor@163.com
|

签名由 网易邮箱大师 定制

On 09/21/2018 22:59, Patrick Marks wrote:

Closed #20.
