### ISSUE TITLE
crash reports

### ISSUE THREAD

**Issue by Rachael-rq** [10XGenomics/vartrix#29]
Hi, 

With command as `/mnt/mcfiles/rlyu/Software/vartrix-v1.1.4-x86_64-linux/vartrix -v $snps -b ../W12/outs/possorted_genome_bam.bam -f $fasta_unzipped \
        -c ../W12/outs/filtered_feature_bc_matrix/barcodes.tsv -o ../output/vartrix/matrix/ --out-variants ../output/vartrix/variants/ --umi --threads 8`

Below is the crash report. Running on around 4k cells.
```

name = 'vartrix'
operating_system = 'unix:Ubuntu'
crate_version = '1.1.3'
explanation = '''
Panic occurred in file 'src/libcore/result.rs' at line 997
'''
method = 'Panic'
backtrace = '''
stack backtrace:
   0:     0x55ffdb9e0b6d - trace
                        at /mnt/home/ian.fiddes/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/backtrace/libunwind.rs:53
                         - trace<closure>
                        at /mnt/home/ian.fiddes/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/backtrace/mod.rs:42
   1:     0x55ffdb9d20fd - handle_dump
                        at /mnt/home/ian.fiddes/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/capture.rs:88
   2:     0x55ffdbb0f587 - {{closure}}
                        at /mnt/yard2/ian/vartrix/<::human_panic::setup_panic macros>:18
   3:     0x55ffdbabe3ae - rust_panic_with_hook
                        at src/libstd/panicking.rs:482
   4:     0x55ffdbabe12e - continue_panic_fmt
                        at src/libstd/panicking.rs:385
   5:     0x55ffdbad1675 - rust_begin_unwind
   6:     0x55ffdbad5fdb - panic_fmt
                        at src/libcore/panicking.rs:85
   7:     0x55ffdbac9b76 - unwrap_failed<std::io::error::Error>
                        at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libcore/macros.rs:17
   8:     0x55ffdbb0c28b - _main
                        at src/main.rs:0
   9:     0x55ffdbb0147c - main
                        at src/main.rs:152
  10:     0x55ffdbaf5e32 - std::rt::lang_start::{{closure}}::h0344adcd09bf53fd
  11:     0x55ffdbb00713 - main
  12:     0x7f67cc825b96 - __libc_start_main
  13:     0x55ffdb9cd1c8 - <unknown>'''
```
Thanks,
Ruqian

**Comment by ifiddes-10x** [comment]
This is weird. Another person saw a similar issue that I was not able to reproduce. The line numbers don't really make any sense. I have two requests: 1) Are you able to send me your input files via the 10x Redstone system? Instructions are here https://support.10xgenomics.com/docs/transfers 2) Are you able to try and compile this yourself instead of using the provided binaries? Does this error still occur?

**Comment by Rachael-rq** [comment]
Thanks for your reply,
I'm going to try option 2 first and will get back to you after that.

Cheers,
Ruqian

**Comment by eyalbenda** [comment]
I got the same error, and solved it by decompressing the barcodes.tsv.gz file from 10x with gzip -d.

**Comment by Rachael-rq** [comment]
> I got the same error, and solved it by decompressing the barcodes.tsv.gz file from 10x with gzip -d.

Thanks, but my input barcode.tsv is already decompressed.

**Comment by dtm2117** [comment]
Following this because I got the exact same error. 

I'm using a VCF 4.2 from a CombineGVCF gatk command.

**Comment by Rachael-rq** [comment]
Hi @ifiddes-10x ,

I tried building from source and re-execute the script. It crashed again. This time it looks different from before: `
stack backtrace:
   0:     0x55f046ed067d - backtrace::backtrace::libunwind::trace::ha96a492236bb4193
                        at /home/AD.EDU.AU/rlyu/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/backtrace/libunwind.rs:53
                         - backtrace::backtrace::trace::hb0e86986094996cb
                        at /home/AD.EDU.AU/rlyu/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/backtrace/mod.rs:42
   1:     0x55f046ebeb7f - human_panic::handle_dump::hcf86d5402bbe42a8
                        at /home/AD.EDU.AU/rlyu/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/capture.rs:88
   2:     0x55f046ea9447 - vartrix::main::{{closure}}::h0928a46b6f8a24bd
                        at /mnt/mcfiles/rlyu/Software/vartrix/vartrix/<::human_panic::setup_panic macros>:18
   3:     0x55f046faceca - std::panicking::rust_panic_with_hook::hffcefc09751839d1
                        at src/libstd/panicking.rs:481
   4:     0x55f046facc3e - std::panicking::continue_panic_fmt::hc0f142c930c846fc
                        at src/libstd/panicking.rs:384
   5:     0x55f046fbde25 - rust_begin_unwind
                        at src/libstd/panicking.rs:311
   6:     0x55f046fc7f8b - core::panicking::panic_fmt::h2daf88b2616ca2b2
                        at src/libcore/panicking.rs:85
   7:     0x55f046feab36 - core::result::unwrap_failed::haf1665968ae46bff
                        at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/macros.rs:18
   8:     0x55f046eb366b - vartrix::_main::hdb29f1b78287761f
                        at src/main.rs:0
   9:     0x55f046ea924a - vartrix::main::h4a82ad930093e2a3
                        at src/main.rs:152
  10:     0x55f046feb1a2 - std::rt::lang_start::{{closure}}::h2d5f46ba4dbe7e23
                        at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/rt.rs:64
  11:     0x55f046ebd2b3 - main
  12:     0x7fba60f8eb96 - __libc_start_main
  13:     0x55f046ea63d9 - _start
  14:                0x0 - <unknown>'''
`

**Comment by pmarks** [comment]
@Rachael-rq - the issue is that `-o` and `--out-variants` need to be concrete filenames, not paths ending in `/`.  I'll add better error messages for that case, sorry for the confusion!

**Comment by Rachael-rq** [comment]
Thanks, @pmarks , that was it! It now runs properly.

Cheers,
R
