### ISSUE TITLE
Annotation of no called, ref/ref, alt/alt, and alt/ref

### ISSUE THREAD

**Issue by zezhuo** [10XGenomics/vartrix#33]
Hi vartrix team,

Thanks for your great packages, I have successfully called mutations from scRNAseq data. But there is some that confuses me. Could you please add annotation of no called, ref/ref, alt/alt, and alt/ref? Does it mean uknow, no mutation, homozygosis, and heterozygosis? 

Regards,
Nelson

```
`# Make the encoding more readable
gt_chr1_1624866$`chr1:1624866` <- str_replace(as.character(gt_chr1_1624866$`chr1:1624866`), "0", "No Call")
gt_chr1_1624866$`chr1:1624866` <- str_replace(as.character(gt_chr1_1624866$`chr1:1624866`), "1", "ref/ref")
gt_chr1_1624866$`chr1:1624866` <- str_replace(as.character(gt_chr1_1624866$`chr1:1624866`), "2", "alt/alt")
gt_chr1_1624866$`chr1:1624866` <- str_replace(as.character(gt_chr1_1624866$`chr1:1624866`), "3", "alt/ref")`
```

**Comment by pmarks** [comment]
Hi @zezhuo - I've updated the README to be more explicit about the definitions. Here are the updated sections: please let me know if it's still unclear.


--scoring-method (-s): The scoring method to be used in the output matrix. In the default consensus mode, the matrix will have a 0 if no reads cover the variant, 1 if all reads at the position support the ref allele, a 2 if one or more reads support the alt allele, and a 3 if one or more reads support both the alt and the ref allele.

```
# Make the encoding more readable
# See documentation of the consensus scoring mode (`-s consensus`)
# No reads detected
gt_chr1_1624866$`chr1:1624866` <- str_replace(as.character(gt_chr1_1624866$`chr1:1624866`), "0", "No Call")
# Only ref detected
gt_chr1_1624866$`chr1:1624866` <- str_replace(as.character(gt_chr1_1624866$`chr1:1624866`), "1", "ref/ref")
# Only alt detected
gt_chr1_1624866$`chr1:1624866` <- str_replace(as.character(gt_chr1_1624866$`chr1:1624866`), "2", "alt/alt")
# Both alleles detected
gt_chr1_1624866$`chr1:1624866` <- str_replace(as.character(gt_chr1_1624866$`chr1:1624866`), "3", "alt/ref")
```
