### ISSUE TITLE
the  problem  of Installation 

### ISSUE THREAD

**Issue by crystal0721** [10XGenomics/vartrix#34]
Dear,
   When we install vartix，we got the error：
  
error: failed to run custom build command for `rust-htslib v0.24.0`

Caused by:
  process didn't exit successfully: `/vartrix/vartrix-master/target/release/build/rust-htslib-c795693bb4b33ad2/build-script-build` (exit code: 101)

We  can not build  rust-htslib v0.24.0 successfully， would you help me？ We had install rust successfuly  and our CentOS is  v6.6.

**Comment by pmarks** [comment]
If you just want to use the tool, please use the pre-built Linux binary: https://github.com/10XGenomics/vartrix/releases/download/v1.1.8/vartrix_linux 
It should work on CentOS 6.6.

To build from source, you need the following packages installed: llvm-dev libclang-dev clang  (these are the Debian package names, there might be different names for CentOS)
Please run with `cargo build -v` to get more detailed error messages.  My guess is that you need to install these libraries.
