### ISSUE TITLE
pre-compiled binaries

### ISSUE THREAD

**Issue by igordot** [10XGenomics/vartrix#39]
I noticed that the tool is still being actively developed, but [releases](https://github.com/10XGenomics/vartrix/releases) stopped. I am mostly concerned about the pre-compiled binaries. Will those still be regularly released?

**Comment by pmarks** [comment]
@igordot we are working on a better Github actions-based binary build setup. Should have it available in the next week or so. What platforms would you like to run on? If Linux, what distro and version are you running?

**Comment by igordot** [comment]
I am on Red Hat Enterprise Linux Server 7.4.

Looking forward to the upcoming updates.

**Comment by jfx319** [comment]
Looks like this issue of automatically compiling binaries is resolved, with the recent github-actions.

However, this change also broke GLIBC backwards compatibility between the manually released binary v1.1.8 and the automated release binary v1.1.13. The prior release was happy with GLIBC_2.17, but the new one seems to want GLIBC_2.18. 

The [10xGenomics os support page](https://support.10xgenomics.com/os-support) linked to by the README on [10xgenomics/vartrix](https://github.com/10XGenomics/vartrix/blob/master/README.md) says OS support is compatible with linux kernel 3.10 and GBU libc 2.17, the newest [v1.1.13 binary release](https://github.com/10XGenomics/vartrix/releases/download/v1.1.13/vartrix_linux) complains that GLIBC_2.18 is not available. Is it possible to make this binary backwards compatible with the other libc versions listed on the main 10x support page? If not, that's okay; can always revert switch to a container. 

```bash
wget https://github.com/10XGenomics/vartrix/releases/download/v1.1.13/vartrix_linux
chmod u+x vartrix_linux
./vartrix_linux
# /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./vartrix_linux)

uname -r
# 3.10.0-957.27.2.el7.x86_64

ldd --version
# ldd (GNU libc) 2.17
```
versus
```bash
wget https://github.com/10XGenomics/vartrix/releases/download/v1.1.8/vartrix_linux
chmod u+x vartrix_linux
./vartrix_linux
# error: The following required arguments were not provided:
#     --bam <FILE>
#    --cell-barcodes <FILE>
#    --fasta <FILE>
#    --vcf <FILE>
#
#USAGE:
#    vartrix_linux --bam <FILE> --bam-tag <bam_tag> --cell-barcodes <FILE> --fasta <FILE> --log-level <log_level> --mapq <INTEGER> --out-matrix <OUTPUT_FILE> --padding <INTEGER> --ref-matrix <OUTPUT_FILE> --scoring-method <scoring_method> --threads <INTEGER> --valid-chars <valid_chars> --vcf <FILE>
#
#For more information try --help
```

**Comment by igordot** [comment]
I am getting the same error. Would be great to have it compiled as v1.1.8.

**Comment by pmarks** [comment]
@igordot @jfx319 I've posted good backward compatible binaries here: https://github.com/10XGenomics/vartrix/releases/tag/v1.1.14

The should work back to CentOS 6 and Ubuntu 12.04, or any other distro with GLIBC at least that recent.

**Comment by igordot** [comment]
Thank you! I can confirm it works for me now.
