### ISSUE TITLE
Generating VCF File

### ISSUE THREAD

**Issue by sahh04** [10XGenomics/vartrix#49]
Hi, 

I am a high school student working on a single cell seq project and I was wondering what tools would be required to generate a VCF file, as I haven't been able to find much information anywhere? 

Thanks

**Comment by pmarks** [comment]
Hi @sahh04, you can use [Freebayes](https://github.com/ekg/freebayes) or [GATK](https://gatk.broadinstitute.org/hc/en-us) to generate VCFs from a BAM file.  You should read up on the general topic of 'variant calling' for next generation sequencing (NGS), then things will make more sense.
