### ISSUE TITLE
MacOS Binary

### ISSUE THREAD

**Issue by rschauner** [10XGenomics/vartrix#51]
I tried to use the pre-compiled binary for MacOS Catalina and could not figure out how to use the download as the instructions in the README and the filenames themselves do not match well. I tried adding the .tar.gz extension to no avail. 

Next, I tried compiling it from source and this is the result:
```
$ cargo build --release -v
     Running `git fetch --tags --force --update-head-ok 'https://github.com/rust-bio/htslib.git' 'refs/heads/*:refs/heads/*'`
error: failed to load source for a dependency on `rust-htslib`

Caused by:
  Unable to update https://github.com/rust-bio/rust-htslib.git?rev=37533bded4692a78cfe080378a09209b95dc3cca#37533bde

Caused by:
  failed to update submodule `htslib`

Caused by:
  failed to fetch submodule `htslib` from https://github.com/rust-bio/htslib.git

Caused by:
  process didn't exit successfully: `git fetch --tags --force --update-head-ok 'https://github.com/rust-bio/htslib.git' 'refs/heads/*:refs/heads/*'` (exit code: 128)
--- stderr
Warning: Permanently added the RSA host key for IP address '140.82.113.4' to the list of known hosts.
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Any recommendation would be useful to either use the pre-compiled binary or to compile it locally.

**Comment by wyattmcdonnell** [comment]
Hi @rschauner--sorry to hear that you hit a wall on this. Quick instructions to get you up and running (just tested on my OS X Catalina machine):

1. Go to the main repo page, on the right hand side you should see a "releases" section right at the top, with `v1.1.16` as the latest.
2. Click on the latest release. That should take you [here](https://github.com/10XGenomics/vartrix/releases/tag/v1.1.16).
3. Download the `vartrix_macos` file.
4. In your Terminal, navigate to wherever you downloaded `vartrix_macos`. 
5. Run the command `chmod +x vartrix_macos` to make VarTrix executable.
6. You should now be able to run VarTrix via `./vartrix_macos` (you may need to give it permission in your System Preferences depending on your current security settings).

Thanks!
