### ISSUE TITLE
Genotyping cancer cells (non-diploid)

### ISSUE THREAD

**Issue by RegnerM2015** [10XGenomics/vartrix#56]
Would vartrix still be appropriate for non-diploid contexts? For example, in cancer cells where regions could be deleted or amplified, would this negatively impact the underlying model used to genotype cells in vartrix? 

Thanks!

**Comment by pmarks** [comment]
@RegnerM2015 yes!  vartrix doesn't make any assumptions about ploidy, it just counts the presence of alt alleles and tells you what cell they came from.  The interpretation in terms to of the true copy number state at locus is up to you :)
