### ISSUE TITLE
vartrix Crash Report

### ISSUE THREAD

**Issue by sanchezy** [10XGenomics/vartrix#66]
Hi, 
I am using vartrix as part of the souporcell pipeline [(https://github.com/wheaton5/souporcell)] and got the following crash reports for 2 of my 16 samples. Could you please advice on how to go around this issue?
Many thanks, 
[report-9cf628a8-32bd-4909-89bc-3f1dae7ab1f5.toml.zip](https://github.com/10XGenomics/vartrix/files/7641180/report-9cf628a8-32bd-4909-89bc-3f1dae7ab1f5.toml.zip)
[report-9e161367-2abf-4850-9291-20c770938cbb.toml.zip](https://github.com/10XGenomics/vartrix/files/7641183/report-9e161367-2abf-4850-9291-20c770938cbb.toml.zip)

**Comment by pmarks** [comment]
Hi @sanchezy  - this is being caused by some weird alignments in your BAM file.  The latest version of vartrix (1.1.22) is more permissive of these reads, and should at least give a better error message if it doesn't understand a read.  Could you please retry with that version? Thanks.
