### ISSUE TITLE
vartrix Crash Report

### ISSUE THREAD

**Issue by sagnikbanerjee15** [10XGenomics/vartrix#80]
Hello,
 
I was executing vartrix and I got the following error message. Please help.
 
name = 'vartrix'
operating_system = 'unix:Unknown'
crate_version = '1.1.3'
explanation = '''
Panic occurred in file 'src/libcore/result.rs' at line 997
'''
method = 'Panic'
backtrace = '''
stack backtrace:
   0:     0x55677fd0ef8d - backtrace::backtrace::libunwind::trace::h0450ee9701db9b56
                        at /mnt/home/ian.fiddes/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/backtrace/libunwind.rs:53
                         - backtrace::backtrace::trace::h9a495a5fb843afd0
                        at /mnt/home/ian.fiddes/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/backtrace/mod.rs:42
   1:     0x55677fd0e0e2 - backtrace::capture::Backtrace::new_unresolved::he8700c7c2914edf9
                        at /mnt/home/ian.fiddes/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/capture.rs:88
                         - backtrace::capture::Backtrace::new::h3441f72ebb513354
                        at /mnt/home/ian.fiddes/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/capture.rs:63
                         - <backtrace::capture::Backtrace as core::default::Default>::default::hdff5cb6156d225b4
                        at /mnt/home/ian.fiddes/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/capture.rs:235
   2:     0x55677fcfd8e2 - human_panic::report::Report::new::h325ba580fbc9e03e
                        at /mnt/home/ian.fiddes/.cargo/registry/src/github.com-1ecc6299db9ec823/human-panic-1.0.1/src/report.rs:45
   3:     0x55677fcfcf97 - human_panic::handle_dump::hbabf58a26cf238b8
                        at /mnt/home/ian.fiddes/.cargo/registry/src/github.com-1ecc6299db9ec823/human-panic-1.0.1/src/lib.rs:197
   4:     0x55677fcceb98 - vartrix::main::{{closure}}::h419645f055558e66
                        at /mnt/yard2/ian/vartrix/<::human_panic::setup_panic macros>:18
   5:     0x55677fe79c69 - std::panicking::rust_panic_with_hook::h744417edfe714d72
                        at src/libstd/panicking.rs:482
   6:     0x55677fe79711 - std::panicking::continue_panic_fmt::h3557b3c3fa21b47b
                        at src/libstd/panicking.rs:385
   7:     0x55677fe795f5 - rust_begin_unwind
                        at src/libstd/panicking.rs:312
   8:     0x55677fe94c5c - core::panicking::panic_fmt::h74ee8034b317ceed
                        at src/libcore/panicking.rs:85
   9:     0x55677fcda460 - core::result::unwrap_failed::h51b8a3c7b11f1009
                        at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libcore/macros.rs:16
  10:     0x55677fcc7a7f - <core::result::Result<T, E>>::unwrap::h6c44aef0ea72ce5e
                        at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libcore/result.rs:798
                         - vartrix::_main::h7b280daad477f5bc
                        at src/main.rs:194
  11:     0x55677fcc05e0 - vartrix::main::h471b1b425af17703
                        at src/main.rs:152
  12:     0x55677fccffa2 - std::rt::lang_start::{{closure}}::h48619bd1f8ea0c15
                        at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/rt.rs:64
  13:     0x55677fe79592 - std::rt::lang_start_internal::{{closure}}::h8ad4264c6b68797c
                        at src/libstd/rt.rs:49
                         - std::panicking::try::do_call::h7a0381557c6c2cee
                        at src/libstd/panicking.rs:297
  14:     0x55677fe81039 - __rust_maybe_catch_panic
                        at src/libpanic_unwind/lib.rs:92
  15:     0x55677fe7a1a5 - std::panicking::try::h72cb0fef6e9c0ab1
                        at src/libstd/panicking.rs:276
                         - std::panic::catch_unwind::hbff071ae76e6f224
                        at src/libstd/panic.rs:388
                         - std::rt::lang_start_internal::he0d8d06abc6f912f
                        at src/libstd/rt.rs:48
  16:     0x55677fccec17 - main
  17:     0x7fcba7bdfbf6 - __libc_start_main
  18:     0x55677fcbda58 - <unknown>'''
 
Thank you,
Sagnik

**Comment by pmarks** [comment]
Hi @sagnikbanerjee15,

You are using a fairly old version of vartrix (1.1.3).  CAn you please try again with the current version (1.1.22) here: https://github.com/10XGenomics/vartrix/releases/tag/v1.1.22

It's fairly likely that this issue has been fixed.  Please make a new issue with the update failure message if the error persists.
